import Head from "next/head";
import { useContext } from "react";
import { Context } from "../context/AppContext";
import { Button, Container } from "react-bootstrap";

export default function Home() {
  const [state, dispatch] = useContext(Context);

  return (
    <div className="">
      <Head>
        <title>Gift your friend a free near account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div className="">
          <p>{JSON.stringify(state)}</p>
          <Button
            variant="primary"
            onClick={async () => {
              dispatch({
                type: "LOGIN",
                user: { name: "Tin", email: "hopthucuatin@gmail.com" },
              });
            }}
          >
            Click me
          </Button>

          <Button
            variant="primary"
            onClick={() => {
              console.log(state);
            }}
          >
            Click me 2
          </Button>
        </div>
      </Container>
    </div>
  );
}
